export const EVENT_SHOW_RESET = 'EVENT_SHOW_RESET'
export const EVENT_SHOW_SET_ERROR = 'EVENT_SHOW_SET_ERROR'
export const EVENT_SHOW_SET_RETRIEVED = 'EVENT_SHOW_SET_RETRIEVED'
export const EVENT_SHOW_TOGGLE_LOADING = 'EVENT_SHOW_TOGGLE_LOADING'
