export const EVENT_DELETE_RESET = 'EVENT_DELETE_RESET'
export const EVENT_DELETE_SET_ERROR = 'EVENT_DELETE_SET_ERROR'
export const EVENT_DELETE_SET_DELETED = 'EVENT_DELETE_SET_DELETED'
export const EVENT_DELETE_TOGGLE_LOADING = 'EVENT_DELETE_TOGGLE_LOADING'
